### ISSUE TITLE
[Version: 0.0.1-nullsafety.0] Error cast for null object

### ISSUE THREAD

**Issue by quanbui1998** [nimbus-org/nimbus4flutter#1]
![image](https://user-images.githubusercontent.com/48360868/113697638-ab507080-96fd-11eb-8931-b6cee6ae49dc.png)

When value ==null => value as F => error. 

Please fix it. Thanks!

**Comment by m-takata** [comment]
Please check the branch release_0.0.1-nullsafety.1, which I have modified.
If you check it, I will release it.

**Comment by quanbui1998** [comment]
@m-takata I checked. It's OK. Thank you so much...

**Comment by m-takata** [comment]
I've released version 0.0.1-nullsafety.1. 
Thank you for reporting bugs.
