### ISSUE TITLE
[Version: 0.0.2] Error cast for null object and function never called

### ISSUE THREAD

**Issue by duchdtran2706** [nimbus-org/nimbus4flutter#2]
The setInput and setOutput will throw error when input or ouput  is null

![Screenshot 2023-09-18 at 15 52 10](https://github.com/nimbus-org/nimbus4flutter/assets/94559040/b9b5abd4-52a4-4c79-a310-8d2f058f20e0)

I see a lot of code like this in your project, server.requestBuilder won't run

You can fix it like this
`server.requestBuilder ?? server.requestBuilder!(request, _method, input))` => `server.requestBuilder?.call(request, _method, input))`

![Screenshot 2023-09-18 at 15 57 09](https://github.com/nimbus-org/nimbus4flutter/assets/94559040/9302c057-f3c2-4020-bf63-e781b7a9955f)

**Comment by m-takata** [comment]
Thanks for pointing that out.

I have made a Pull Request per your suggestion and would like you to check it out.

https://github.com/nimbus-org/nimbus4flutter/pull/3

**Comment by duchdtran2706** [comment]
@m-takata 

I checked. The problem is resolved
